// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error('Missing Supabase environment variables. Please check your .env file.');
}

// Singleton pattern to avoid multiple client instances
let supabaseInstance: ReturnType<typeof createClient>;
let authenticatedInstance: ReturnType<typeof createClient> | null = null;

// Create Supabase client with native third-party auth support
export const supabase = (() => {
  if (supabaseInstance) return supabaseInstance;
  
  // Always use the production Supabase URL since Edge Functions are deployed
  const baseUrl = supabaseUrl || '';
  
  // Create a client with the global configuration
  supabaseInstance = createClient(baseUrl, supabaseAnonKey || '', {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: false,
      flowType: 'pkce',
    },
    global: {
      headers: {
        'X-Client-Info': 'supabase-js-web/2.x'
      }
    }
  });
  
  return supabaseInstance;
})();

// Helper to get the current Supabase session
export async function getSupabaseSession() {
  const { data: { session } } = await supabase.auth.getSession();
  return session;
}

// Helper to sign out from Supabase
export async function signOutFromSupabase() {
  const { error } = await supabase.auth.signOut();
  return { error };
}

// Helper to create a Supabase client with Clerk session token
// This uses Clerk's native integration approach with singleton pattern
export function createSupabaseClientWithClerkToken(sessionToken: string | null) {
  // If we already have an authenticated instance and the token is the same, reuse it
  if (authenticatedInstance && sessionToken) {
    return authenticatedInstance;
  }
  
  // Create new authenticated instance
  authenticatedInstance = createClient(supabaseUrl || '', supabaseAnonKey || '', {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: false,
      flowType: 'pkce',
    },
    global: {
      headers: {
        Authorization: sessionToken ? `Bearer ${sessionToken}` : '',
        'apikey': supabaseAnonKey || '',
      },
    },
  });
  
  return authenticatedInstance;
}

// Alternative approach using Clerk's accessToken function
export async function createClerkSupabaseClient(getToken: () => Promise<string | null>) {
  const token = await getToken();
  return createSupabaseClientWithClerkToken(token);
}

// Clear authenticated instance when needed (e.g., on logout)
export function clearAuthenticatedInstance() {
  authenticatedInstance = null;
}