// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Do not hard-crash the app in production if envs are missing; log clearly instead.
if (!supabaseUrl || !supabaseAnonKey) {
  // eslint-disable-next-line no-console
  console.error(
    'Missing Supabase environment variables: VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY. ' +
    'The app will load, but Supabase features will not function until these are set.'
  );
}

// Singleton pattern to avoid multiple client instances
let supabaseInstance: ReturnType<typeof createClient> | undefined;

function createStubClient(): any {
  const notConfigured = () => {
    throw new Error('Supabase is not configured. Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY.');
  };
  return {
    auth: {
      getSession: async () => ({ data: { session: null }, error: new Error('Supabase not configured') }),
      signOut: async () => ({ error: new Error('Supabase not configured') }),
    },
    from: () => ({ select: notConfigured, insert: notConfigured, update: notConfigured, delete: notConfigured }),
    functions: { invoke: async () => ({ data: null, error: new Error('Supabase not configured') }) },
  };
}

// Create Supabase client with Clerk integration
export const supabase = (() => {
  if (supabaseInstance) return supabaseInstance as any;

  // Only create a real client when envs are present to avoid runtime URL errors
  if (supabaseUrl && supabaseAnonKey) {
    // Create a client with Clerk-compatible configuration
    supabaseInstance = createClient(supabaseUrl, supabaseAnonKey, {
      auth: {
        autoRefreshToken: false, // Disable auto-refresh to avoid conflicts with Clerk
        persistSession: false,   // Disable session persistence for Clerk integration
        detectSessionInUrl: false,
        flowType: 'pkce',
        // Use a dedicated storageKey to avoid collisions
        storageKey: 'sb-clerk-integrated',
      },
      global: {
        headers: {
          'X-Client-Info': 'supabase-js-web/2.x'
        }
      }
    });
    return supabaseInstance;
  }

  // Fallback stub to keep app rendering even if envs are missing
  return createStubClient();
})();

// Helper to get the current Supabase session
export async function getSupabaseSession() {
  const { data: { session } } = await supabase.auth.getSession();
  return session;
}

// Helper to sign out from Supabase
export async function signOutFromSupabase() {
  const { error } = await supabase.auth.signOut();
  return { error };
}

// Singleton for Clerk-authenticated Supabase client
let clerkSupabaseInstance: ReturnType<typeof createClient> | null = null;
let currentClerkToken: string | null = null;

// Helper to create a Supabase client with Clerk session token
// This uses Clerk's native integration approach with singleton pattern
export function createSupabaseClientWithClerkToken(sessionToken: string | null) {
  // If we have a cached instance with the same token, return it
  if (clerkSupabaseInstance && currentClerkToken === sessionToken) {
    return clerkSupabaseInstance;
  }

  // Create or update the singleton instance
  currentClerkToken = sessionToken;
  clerkSupabaseInstance = createClient(supabaseUrl || '', supabaseAnonKey || '', {
    auth: {
      autoRefreshToken: false, // Disable to avoid conflicts with main client
      persistSession: false,   // Disable to avoid conflicts with main client
      detectSessionInUrl: false,
      flowType: 'pkce',
      // Use a distinct storageKey for Clerk-authenticated client to avoid GoTrue warnings
      storageKey: 'sb-clerk-auth',
    },
    global: {
      headers: {
        Authorization: sessionToken ? `Bearer ${sessionToken}` : '',
        'apikey': supabaseAnonKey || '',
      },
    },
  });

  return clerkSupabaseInstance;
}

// Alternative approach using Clerk's accessToken function
export async function createClerkSupabaseClient(getToken: () => Promise<string | null>) {
  const token = await getToken();
  return createClient(supabaseUrl || '', supabaseAnonKey || '', {
    auth: {
      // Keep refresh enabled but do not persist session to avoid storage collisions
      autoRefreshToken: true,
      persistSession: false,
      detectSessionInUrl: false,
      flowType: 'pkce',
      storageKey: 'sb-clerk-auth',
    },
    global: {
      headers: {
        Authorization: token ? `Bearer ${token}` : '',
      },
    },
  });
}