// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tusdijypopftcmlenahr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1c2Rpanlwb3BmdGNtbGVuYWhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwMTg0MzgsImV4cCI6MjA1NTU5NDQzOH0.Q2IaqjCAz7lOqyJI8COveiyA_9W1kziBqwHK5JSJJMU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);