// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error('Missing Supabase environment variables');
}

// For local development, we'll modify the auth settings
export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
    // Debug mode can help with authentication issues
    debug: true,
    // Custom auth UI settings
    ui: {
      // These settings will be used by the Auth UI
      theme: 'dark',
      providers: ['google'],
      // Hide Supabase branding
      hideSupabaseBranding: true,
      // Custom labels
      labels: {
        button: {
          signIn: 'Sign in to FlipMyEra',
          signUp: 'Create FlipMyEra Account'
        },
        header: {
          signIn: 'Welcome to FlipMyEra',
          signUp: 'Join FlipMyEra'
        }
      }
    }
  },
  global: {
    // Disable headers that might be causing captcha issues
    headers: {
      'X-Client-Info': 'supabase-js-web/2.x'
    }
  }
});

// Log authentication setup for debugging
console.log('Supabase Auth Configuration:', {
  url: supabaseUrl,
  authFlowType: 'pkce',
  providers: ['google', 'email'],
  debug: true
});